services :
  app :
    build       :
      context    : .
      dockerfile : Dockerfile
    volumes     :
      - .:/var/www/html:cached
    depends_on  :
      db :
        condition : service_healthy
    environment :
      DATABASE_URL : mysql://user:as86dfgas@db:3306/tinypixelblog
    healthcheck :
      test     : [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
      interval : 10s
      timeout  : 5s
      retries  : 3
  nginx :
    image      : nginx:latest
    depends_on :
      - app
    ports      :
      - "8000:80" # Map port 8000 on the host to port 80 on the container
    volumes    :
      - .:/var/www/html:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db  :
    image       : mysql:8.0
    environment :
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE      : tinypixelblog
      MYSQL_USER          : user
      MYSQL_PASSWORD      : as86dfgas
    ports       :
      - "3308:3306"
    healthcheck :
      test     : [ "CMD-SHELL", "mysqladmin ping -h localhost --silent || exit 1" ]
      interval : 10s
      timeout  : 10s
      retries  : 5
